[package]
name = "lennard_jonesium"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lennard_jonesium"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

quarkstrom = {path = "./quarkstrom"}
